[mixer]
nosound=true

[midi]
mididevice=none

[sblaster]
sbtype=none

[speaker]
pcspeaker=false

[autoexec]

mount l /tmp
mount c ./
c:
cd c:\bld_dos\bin
larse.exe --version
larse.exe -x "(my-example (some-list (vals 1 2 3) \"hi\"))"
pause
exit
