
#include "rasgl/core/debug.h"
#include "rasgl/core/plane.h"
#include "rasgl/core/repr.h"
#include "test_support.h"
#include <math.h>

TEST(TEST_PLANE)
{
    // Test case generated by terrain_d:
    // Plane 1: [
    // [    -0.18973
    // [     0.83205
    // [    -0.52124
    // [   355.17627]]
    // Plane 2: [
    // [     0.34209
    // [     0.00000
    // [     0.93967
    // [  7178.25342]]
    // Plane 3: [
    // [    -0.97159
    // [     0.00000
    // [    -0.23665
    // [   773.27783]]
    // Plane intersect point: [
    // [  2915.04126
    // [ -5212.57520
    // [ -8700.36133
    // [     0.00000]]

    char buffer[255];

    RasPlane pl1 = {
        .normal = {
            .x = float_to_fixed_16_16(-0.18973),
            .y = float_to_fixed_16_16(0.83205),
            .z = float_to_fixed_16_16(-0.52124) },
        .distance = float_to_fixed_16_16(355.17627)
    };

    RasPlane pl2 = {
        .normal = {
            .x = float_to_fixed_16_16(0.34209),
            .y = float_to_fixed_16_16(0.0),
            .z = float_to_fixed_16_16(0.93967) },
        .distance = float_to_fixed_16_16(7178.25342)
    };

    RasPlane pl3 = {
        .normal = {
            .x = float_to_fixed_16_16(-0.97159),
            .y = float_to_fixed_16_16(0.0),
            .z = float_to_fixed_16_16(-0.23665) },
        .distance = float_to_fixed_16_16(773.27783)
    };

    Point3f result;

    core_get_3_plane_intersection(&pl1, &pl2, &pl3, &result);
    ras_log_info("3 plane intersect result: %s\n", repr_point3f(buffer, sizeof buffer, &result));
    return false;
}
