#ifndef CORE_COLOR_H
#define CORE_COLOR_H

#define RAS_COLOR_RAMPS 3
#define RAS_COLOR_RAMP_SIZE 8 // Number of shades
#define RAS_COLOR_RAMP_OFFSET_GREY 0
#define RAS_COLOR_RAMP_OFFSET_RED RAS_COLOR_RAMP_SIZE
#define RAS_COLOR_RAMP_OFFSET_BLUE RAS_COLOR_RAMP_SIZE * 2
#define RAS_COLOR_RAMP_OFFSET_GREEN RAS_COLOR_RAMP_SIZE * 3
#define RAS_COLOR_RAMP_MIN_SHADE 5

#endif
