name: Build Larse

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - lar-ci
    paths:
      - 'larse/**'
      - '.github/workflows/build-larse.yml'

  pull_request:
    paths:
      - 'larse/**'
      - '.github/workflows/build-larse.yml'

permissions:
  contents: write

jobs:

  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: larse

    steps:
      - uses: actions/checkout@v5

      - name: Configure
        run: cmake -S . -B build

      - name: Build tests
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure --output-junit tests.xml

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "build/**/tests*.xml"
        if: always()

  posix:
    runs-on: ubuntu-latest
    needs: tests

    defaults:
      run:
        working-directory: larse

    steps:
      - uses: actions/checkout@v5

      - name: Configure
        run: cmake -S . -B build

      - name: Get version
        id: version
        shell: bash
        run: |
          BASE_VERSION=$(grep '^CMAKE_PROJECT_VERSION:STATIC=' build/CMakeCache.txt | cut -d= -f2)
          SHORT_SHA="${GITHUB_SHA::7}"
          VERSION="${BASE_VERSION}+${GITHUB_RUN_NUMBER}.${SHORT_SHA}"

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: |
          tar -czf \
            "larse-${{ steps.version.outputs.version }}-posix.tar.gz" \
            -C build/bin .

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: posix
          path: larse/larse-${{ steps.version.outputs.version }}-posix.tar.gz

  dos:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Placeholder
        run: |
          echo "DOS build not implemented yet"

      # Future:
      #
      # - uses: actions/checkout@v5
      # - build DOS
      # - zip artifacts
      # - upload artifact

  release:
    runs-on: ubuntu-latest

    needs:
      - tests
      - posix
      - dos

    if: github.event_name == 'push'

    steps:
      - uses: actions/download-artifact@v5
        with:
          path: artifacts

      - name: List artifacts
        run: find artifacts

      - name: Update CI Release
        uses: ncipollo/release-action@v1
        with:
          tag: ci
          name: Continuous Build
          prerelease: true
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          makeLatest: false
          artifacts: |
            artifacts/**/*.tar.gz
            artifacts/**/*.zip
