name: Build RasGL

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - 'rasgl/**'
      - '.github/workflows/build-rasgl.yml'

  pull_request:
    paths:
      - 'rasgl/**'
      - '.github/workflows/build-rasgl.yml'

permissions:
  contents: write

jobs:

  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: rasgl

    steps:
      - uses: actions/checkout@v5

      - name: Configure
        run: cmake -S . -B build -DDEBUG=0

      - name: Build tests
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure --output-junit tests.xml

      - name: List files
        run: find . -name '*.xml'
      - name: List files
        run: find . -name '*.lsp'
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "rasgl/build/**/tests*.xml"
        if: always()
